use_frameworks!

platform :ios, '12.0'

target 'TKUISDK_iOS_Example' do
  pod 'TKUISDK_iOS', :path => '../'
  pod 'TKScreenShareService'
  
  pod 'Masonry'
  pod 'Bugly', '2.5.0'
  pod 'UMCommon', '7.2.5'
  pod 'UMShare/UI', '6.10.1'
  # 微信完整版
  pod 'UMShare/Social/WeChat', '6.10.1'
  # 集成QQ/QZone/TIM(完整版7.6M)
  pod 'UMShare/Social/QQ', '6.10.1'
  # 集成新浪微博(完整版25.3M)
  pod 'UMShare/Social/Sina', '6.10.1'
  # 集成微软实时语音
  pod 'MicrosoftCognitiveServicesSpeech-iOS'
end

target 'TKScreenRecorder' do
  pod 'TKScreenShareService'
end
